OPCODES = {
    'CLIENT_INITIALIZE': 0,
    'CONNECTION_INITIALIZED': 1,
    'CONNECTION_CLOSED': 2,
    'CONNECTION_ERROR': 3,
    'CLIENT_DISCONNECT': 4,
    'PING': 5,  # for tests
    'IS_AVAILABLE': 6,
    'REGISTER': 7,
    'SEND_MAIL': 8,
    'GET_MAILS': 9,
    'UPLOAD_FILE': 10,
    'PARSE_ERROR': 11,

    'UNKNOWN_OPCODE': -1
}
